version: "3.9"
services:
  api:
    build:
      context: ./api
      network: host
    environment: 
      - DATA_DIR=/app/data
      - FRONTEND_URL=http://localhost:3000
    ports:
    - 5000:5000
    volumes:
      - everything:/app/data
  web:
    build:
      context: ./frontend
      network: host
    ports:
    - 3000:3000
volumes:
  everything:
    external: true